### PR TITLE
fix for issue #112

### PR DESCRIPTION
**Pull request by tfritsch-km**
### What is the purpose of this pull request?

This PR is intented to resolve issue #112 ie. preserving cursor position and section folding when using `"csscomb.formatOnSave": true,`

### What changes did you make? (Give an overview)

copy/paste of the code running when using Command Palette "CSSComb: format styles" (onCommand) into the code running when saving file (`onSave`).
There definitely should be some refactoring to do but since I'm not sure of what I'm really doing, I prefer leaving as is, since it seems to be working. 🎉

### CODE REVIEW

**Comment by mrmlnc** [comment]
Hello, @tfritsch-km,

Unfortunately, this solution has a regression. For example, after it changes, we will only use the formatter for an open document when many documents have been modified.

**Before**

0. Change the `smoke/test.css` and `test.less` file (add whitespace, for example)
1. Run: <kbd>F1</kbd> -> `File: Save all`
2. All files will be saved using the formatter.

**After**

0. Change the `smoke/test.css` and `test.less` file (add whitespace, for example)
1. Run: <kbd>F1</kbd> -> `File: Save all`
2. All files will be saved, but the formatter will be applied only to the current editor.

**Comment by tfritsch-km** [comment]
Thank you @mrmlnc for the review. I didn't see the bug since I never use the "save all" feature, thank you for pointing it ! Any idea of a way to do it ?

**Comment by tfritsch-km** [comment]
@mrmlnc I just pushed a fix for the case you mentioned (Save all). 
If you've got some time to give it a try, I think it works quite well (even i the code itselft, is not really what I call beautiful waiting for https://github.com/Microsoft/vscode/issues/15178 to evolve) 😄

**Comment by tfritsch-km** [comment]
Hello @mrmlnc have you found any new bug on this PR ? Any chance it gets merged ?

**Comment by tfritsch-km** [comment]
Hello @mrmlnc sorry to insist but is there something I could do to help or ease the review process ? 
You asked me to do a PR -that I did 3 months ago- but maybe there is something that is missing in what I did ?
Feel free to tell me if you need something more from me, I understand that you've got plenty of work with others repos, but I think this PR could help people working with this extension and csscomb 😉

**Comment by mrmlnc** [comment]
Thank you for that input, @tfritsch-km 🎉 🌮 

I am sorry to everyone for the long wait.

I will add just one commit that will correct the formatting and predicate of the condition for finding a similar document.

**Pull request merged**
